DEB_FILE_NAME = NsightSystems-linux-cli-public-2024.4.1.61-3431596.deb

.PHONY: install
install:
	wget https://developer.nvidia.com/downloads/assets/tools/secure/nsight-systems/2024_4/${DEB_FILE_NAME}
	dpkg -i ${DEB_FILE_NAME}

